global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: hyperf
    static_configs:
      - targets: ['api_gateway:9501']
  - job_name: rabbitmq
    metrics_path: /metrics
    static_configs:
      - targets: ['rabbitmq:15672']
    basic_auth:
      username: ${RABBITMQ_USER}
      password: ${RABBITMQ_PASSWORD}