name: CI Pipeline

on: [ push, pull_request ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Copy .env file
        run: cp .env-example .env

      - name: Build Docker images
        run: docker compose build

      - name: Start services
        run: docker compose up -d

      - name: Wait for services to be healthy
        run: |
          sleep 30  
          docker compose ps
      - name: Run migrations and seeders
        run: docker compose exec -T api_gateway php bin/hyperf.php migrate --seed

      - name: Run code quality check (PHPMD)
        run: docker compose run --rm phpqa phpmd app text phpmd.xml | grep -v 'Deprecated'

      - name: Run tests
        run: docker compose exec -T api_gateway composer test

      - name: Shutdown services
        run: docker compose down